<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Voluptate error optio nostrum consequatur quod corporis.',
                'description' => '<p>Possimus temporibus unde aut corrupti et nam esse officia at officiis quia unde aut.</p>',
                'price' => 21.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:00',
                'updated_at' => '2020-07-06 04:19:45',
                'shop_id' => 0,
            ),
            1 => 
            array (
                'id' => 3,
                'name' => 'fancy shirt',
                'description' => '<p>fancy shirts</p>',
                'price' => 18.0,
                'cover_img' => 'products\\July2020\\Kvwwhrha1zH3EomZL0SM.jpg',
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-06 04:34:42',
                'shop_id' => 0,
            ),
            2 => 
            array (
                'id' => 4,
                'name' => 'Autem rerum cupiditate error ut.',
                'description' => 'Qui vero dolor distinctio facilis animi qui.',
                'price' => 16.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'Praesentium debitis in et doloribus.',
                'description' => 'Veritatis porro amet delectus expedita deserunt sunt ab quia minus expedita.',
                'price' => 15.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Id est est blanditiis neque eaque voluptas.',
                'description' => 'Id consequatur impedit in molestiae similique possimus laboriosam et repudiandae aperiam.',
                'price' => 49.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Voluptate tempora voluptatem voluptas est illum.',
                'description' => 'Voluptas iusto sit non nobis hic non molestias consequuntur cupiditate.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Pariatur mollitia aliquam rerum dolorem vitae mollitia.',
                'description' => 'Totam et minus vel eius adipisci neque mollitia omnis inventore.',
                'price' => 10.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Molestiae et quo illo quia corporis.',
                'description' => 'Voluptas accusantium dolores itaque commodi fugiat rem.',
                'price' => 20.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Necessitatibus voluptatem iste recusandae consequatur unde aut.',
                'description' => 'Modi laboriosam reiciendis voluptate impedit neque officia iusto autem id adipisci enim aut.',
                'price' => 26.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'Iure nemo eum est consequatur eos beatae.',
                'description' => 'Modi qui officia voluptas facilis voluptates itaque ipsum velit eaque.',
                'price' => 49.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'Eligendi perspiciatis ea eum deserunt nobis.',
                'description' => 'Saepe nisi quam sed recusandae ex omnis.',
                'price' => 26.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'Omnis consequuntur quo molestias et.',
                'description' => 'Commodi cumque maiores error occaecati dolorem dolorem.',
                'price' => 34.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'Alias eos omnis in debitis.',
                'description' => 'Sed itaque quasi dolores labore pariatur ut suscipit dolores reprehenderit tenetur non.',
                'price' => 40.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'Laboriosam adipisci optio praesentium similique.',
                'description' => 'Expedita mollitia distinctio vitae porro nihil rerum delectus et quis sit sapiente et ullam.',
                'price' => 17.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'Numquam perferendis eum sit repellat.',
                'description' => 'Eos sit quod aut ut dolorem nemo iure quisquam harum enim nulla rem rerum.',
                'price' => 29.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'Expedita quo aut facere.',
                'description' => 'Dicta ea ab molestiae qui rem blanditiis molestiae autem officiis et sed alias.',
                'price' => 42.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'Molestiae sit aliquid blanditiis.',
                'description' => 'Quasi ratione dolores quis placeat recusandae in dolorem nihil quo voluptate odit.',
                'price' => 30.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Numquam rerum ut aut possimus explicabo.',
                'description' => 'Numquam enim ut ad itaque aspernatur voluptas odit.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'Quos eos ea quo repudiandae.',
                'description' => 'Qui enim quisquam corrupti facere et fugiat sapiente harum repudiandae quis modi facilis.',
                'price' => 32.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'Qui est suscipit autem exercitationem.',
                'description' => 'Animi sint dolor impedit aut adipisci eum unde fugiat blanditiis ex nostrum.',
                'price' => 42.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'Fugit suscipit occaecati culpa ut unde itaque.',
                'description' => 'Deserunt asperiores delectus recusandae voluptatem distinctio itaque beatae.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'Assumenda nam consequuntur deserunt.',
                'description' => 'Repudiandae praesentium in mollitia id vel magni ducimus distinctio illum vel.',
                'price' => 27.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'Eaque dolores porro id nesciunt enim.',
                'description' => 'Rerum officiis reprehenderit repellendus accusantium est qui aut id ipsam cum.',
                'price' => 39.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'Sit qui natus eos eveniet alias sunt.',
                'description' => 'Debitis quidem est velit adipisci aut voluptates nesciunt.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'Deserunt ut aut rem enim mollitia.',
                'description' => 'Repellat occaecati unde nihil provident facilis alias ipsam ut quibusdam aspernatur id.',
                'price' => 23.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'Repellat placeat similique nostrum.',
                'description' => 'Aliquam doloremque aut a minima tempore magnam et et enim aspernatur quia.',
                'price' => 32.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'Officiis quis ut et quod sed.',
                'description' => 'Aut vel et ut at doloribus consequatur natus qui sed enim aut temporibus.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'Laboriosam accusamus deleniti consequatur culpa.',
                'description' => 'Quia quam itaque et consequatur optio voluptatem eos fuga molestias est reprehenderit autem.',
                'price' => 27.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'Quidem voluptas eius beatae optio enim quod.',
                'description' => 'Praesentium blanditiis commodi ut saepe commodi aperiam vero veniam ullam est quos error iste.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'Doloremque rerum suscipit ipsa.',
                'description' => 'Quidem nihil recusandae nam aut enim distinctio quia accusamus porro non.',
                'price' => 27.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'Et aut omnis itaque.',
                'description' => 'Praesentium rerum sint qui blanditiis hic velit est sit nisi alias molestiae saepe alias.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'Magni dolorum eum omnis.',
                'description' => 'Vel consequatur rerum dicta assumenda rerum quia.',
                'price' => 39.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'Suscipit ex qui occaecati et.',
                'description' => 'Possimus quas nemo architecto modi tempora officia amet.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'Enim perspiciatis molestiae tenetur ipsam.',
                'description' => 'Neque quis consequatur quis culpa nemo rerum.',
                'price' => 26.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'Suscipit aliquam eaque fugit placeat.',
                'description' => 'Hic laboriosam harum aut atque quam labore qui voluptatum.',
                'price' => 13.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'Nostrum ratione suscipit aut sit voluptas.',
                'description' => 'Sint consequuntur consequatur enim sapiente in ullam repellat quas.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'Optio asperiores adipisci veritatis animi dolor.',
                'description' => 'Ut excepturi repudiandae sint est hic impedit temporibus aut incidunt sint magnam dolores.',
                'price' => 22.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'Deleniti sapiente fuga minima quae.',
                'description' => 'Dolore consectetur odio atque doloremque fuga suscipit eos voluptatem sit.',
                'price' => 41.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'Atque animi aspernatur et officiis.',
                'description' => 'Error cum accusantium et reprehenderit architecto id ab perspiciatis est eos maxime esse.',
                'price' => 37.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'Ipsum incidunt iusto consectetur eos.',
                'description' => 'Iste consectetur cumque nobis id eum eaque ab.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'Est labore harum quia.',
                'description' => 'Qui enim iste temporibus est qui quas itaque quia sunt ratione iure unde quam.',
                'price' => 28.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'Ut sit deleniti in cum.',
                'description' => 'Et dolor itaque aspernatur et non ut rerum sapiente iste.',
                'price' => 47.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'Non soluta atque et.',
                'description' => 'Aliquid ea ullam voluptatem iure ut rerum fugit ratione et tempore sunt ut.',
                'price' => 44.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'Pariatur aut quia consequatur qui culpa aliquid.',
                'description' => 'Qui et repellendus repellat consectetur sint cupiditate et aut suscipit.',
                'price' => 48.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'Aut quod fugiat qui et doloribus.',
                'description' => 'Suscipit accusantium est modi nam et consequuntur dolor.',
                'price' => 28.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'Animi minima repudiandae voluptas eius.',
                'description' => 'Ut sit vel autem tempore repellat est voluptates.',
                'price' => 34.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'Omnis sapiente repudiandae nostrum.',
                'description' => 'Non expedita consequatur magni aut in eos architecto incidunt et facere.',
                'price' => 13.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'Sequi et sed ut.',
                'description' => 'Ex in ut nostrum error dolorem numquam id sit aspernatur repellat ducimus non assumenda.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'Sed sit optio fugiat voluptate.',
                'description' => 'Totam ipsum veniam accusamus est est natus blanditiis.',
                'price' => 33.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-05 04:42:36',
                'updated_at' => '2020-07-05 04:42:36',
                'shop_id' => 0,
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'Illo ullam itaque neque ab.',
                'description' => 'Animi quia nam nisi qui a aut aut minima quas eligendi corrupti.',
                'price' => 13.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'Excepturi qui aspernatur sed quos totam.',
                'description' => 'A blanditiis consectetur ea eos ut perferendis inventore voluptas et et voluptas.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 1,
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'Similique non necessitatibus iste.',
                'description' => 'Et quo non et fugiat ratione explicabo commodi tempore est.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'Et iste mollitia veniam optio eius.',
                'description' => 'Laudantium et non in doloribus alias iste ducimus ut itaque architecto eveniet nihil unde quis.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            53 => 
            array (
                'id' => 55,
                'name' => 'Perferendis delectus labore minus eum perferendis.',
                'description' => 'Incidunt est voluptas iure natus quisquam est sequi cupiditate sit architecto quam beatae.',
                'price' => 32.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            54 => 
            array (
                'id' => 56,
                'name' => 'Sunt quis qui vitae.',
                'description' => 'Ex impedit temporibus aliquid illum nemo suscipit nihil ducimus odit.',
                'price' => 19.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            55 => 
            array (
                'id' => 57,
                'name' => 'Tempore sit vel fuga.',
                'description' => 'Nihil libero et in repellendus ad quam eum.',
                'price' => 21.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 1,
            ),
            56 => 
            array (
                'id' => 58,
                'name' => 'Omnis eius illo expedita aut quo.',
                'description' => 'Aut sint vel dolorum itaque libero assumenda exercitationem recusandae aut eveniet a omnis illum.',
                'price' => 42.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            57 => 
            array (
                'id' => 59,
                'name' => 'Architecto voluptatibus officiis distinctio debitis.',
                'description' => 'Maxime praesentium voluptates assumenda quaerat numquam quos et aliquid et in dolores a.',
                'price' => 42.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            58 => 
            array (
                'id' => 60,
                'name' => 'Qui iste repellat excepturi ipsa.',
                'description' => 'Totam accusantium fuga est cumque sint veritatis accusamus nisi ullam a error eum.',
                'price' => 32.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            59 => 
            array (
                'id' => 61,
                'name' => 'Quidem commodi ea recusandae sit.',
                'description' => 'Enim laborum ad debitis iste esse aut iusto.',
                'price' => 32.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            60 => 
            array (
                'id' => 62,
                'name' => 'Fugit qui dignissimos porro fugiat quia et.',
                'description' => 'Minima et fugit consequatur officia dolores voluptatum quaerat nulla praesentium aut vel expedita.',
                'price' => 44.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            61 => 
            array (
                'id' => 63,
                'name' => 'Omnis architecto iusto et et fugiat.',
                'description' => 'Iusto praesentium ea alias quis est quasi corporis voluptas.',
                'price' => 39.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 1,
            ),
            62 => 
            array (
                'id' => 64,
                'name' => 'Ut eos voluptate possimus dolor beatae.',
                'description' => 'Sapiente quos in quaerat dolor expedita non doloremque corporis est soluta consequatur cumque.',
                'price' => 44.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            63 => 
            array (
                'id' => 65,
                'name' => 'Ullam voluptas harum ea.',
                'description' => 'Quis modi asperiores ipsum cupiditate nisi sed perspiciatis aut.',
                'price' => 31.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            64 => 
            array (
                'id' => 66,
                'name' => 'Excepturi accusantium voluptas cumque aut.',
                'description' => 'Itaque aperiam ea eius id omnis quia corporis eum ut itaque mollitia.',
                'price' => 15.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            65 => 
            array (
                'id' => 67,
                'name' => 'Voluptatem sint voluptas ipsa aliquid quae.',
                'description' => 'Qui autem dolorem sequi aliquam similique nam non aperiam iusto illo nulla.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 1,
            ),
            66 => 
            array (
                'id' => 68,
                'name' => 'Corrupti beatae qui unde consequuntur eum.',
                'description' => 'Molestiae itaque qui voluptas nihil eos modi numquam magnam mollitia odio magni.',
                'price' => 28.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 1,
            ),
            67 => 
            array (
                'id' => 69,
                'name' => 'Ut eveniet quis quis.',
                'description' => 'Quas quam a quasi consequatur consectetur aspernatur dolores eum.',
                'price' => 13.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            68 => 
            array (
                'id' => 70,
                'name' => 'Ea sit rerum accusantium.',
                'description' => 'Quod quo ipsum est quia voluptatem nulla voluptatum.',
                'price' => 39.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            69 => 
            array (
                'id' => 71,
                'name' => 'Sapiente eligendi aut libero.',
                'description' => 'Deserunt et unde eos pariatur a ab.',
                'price' => 30.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            70 => 
            array (
                'id' => 72,
                'name' => 'Ipsam doloremque voluptatibus optio non in velit.',
                'description' => 'Architecto et neque sunt quasi odio enim quasi a.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            71 => 
            array (
                'id' => 73,
                'name' => 'Sit rerum aut ad et sunt.',
                'description' => 'Quos ea deserunt recusandae mollitia ut omnis tenetur dolorum exercitationem unde quia et quis.',
                'price' => 29.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            72 => 
            array (
                'id' => 74,
                'name' => 'Deleniti quae ut explicabo repellat.',
                'description' => 'Nesciunt cupiditate quidem iure eligendi tenetur temporibus modi quia itaque accusamus sit a recusandae.',
                'price' => 26.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            73 => 
            array (
                'id' => 75,
                'name' => 'Quo et corrupti rerum et aut rerum provident.',
                'description' => 'Sint est et unde aut rem ipsa molestiae excepturi libero in qui sit error.',
                'price' => 29.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            74 => 
            array (
                'id' => 76,
                'name' => 'Suscipit ratione dicta asperiores ducimus.',
                'description' => 'Et voluptatem laborum in nihil repudiandae autem.',
                'price' => 18.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 1,
            ),
            75 => 
            array (
                'id' => 77,
                'name' => 'Dicta exercitationem tempora ut quia nulla omnis.',
                'description' => 'Alias debitis autem aut quasi nihil voluptates perferendis repellat sit dolores.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 3,
            ),
            76 => 
            array (
                'id' => 78,
                'name' => 'Ut beatae consequatur nulla alias nihil.',
                'description' => 'Et mollitia fuga laborum nihil sequi at nulla recusandae aut ipsa aliquam.',
                'price' => 14.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 1,
            ),
            77 => 
            array (
                'id' => 79,
                'name' => 'Officiis ipsum cumque non maiores harum omnis.',
                'description' => 'Dolores necessitatibus et ad inventore qui blanditiis ducimus.',
                'price' => 48.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            78 => 
            array (
                'id' => 80,
                'name' => 'Tenetur est sint nostrum quibusdam nobis deserunt.',
                'description' => 'Vitae nobis et consequatur autem numquam provident.',
                'price' => 13.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:56',
                'updated_at' => '2020-07-06 06:22:56',
                'shop_id' => 2,
            ),
            79 => 
            array (
                'id' => 81,
                'name' => 'Aliquam dolorum qui inventore fugiat mollitia sed.',
                'description' => 'Ut itaque dolor id at nulla voluptas veritatis aut vero ea esse.',
                'price' => 22.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            80 => 
            array (
                'id' => 82,
                'name' => 'Quas laborum quis debitis optio nisi quae.',
                'description' => 'Velit assumenda harum eos aliquam quod hic enim autem laudantium distinctio ipsam consequuntur vel.',
                'price' => 50.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 3,
            ),
            81 => 
            array (
                'id' => 83,
                'name' => 'Id sit neque ut aut eum.',
                'description' => 'Molestiae suscipit omnis molestiae minus asperiores est est quam corporis voluptatibus odit.',
                'price' => 27.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 2,
            ),
            82 => 
            array (
                'id' => 84,
                'name' => 'Rerum libero nihil sint minus.',
                'description' => 'Ipsa fugiat distinctio veritatis deleniti in aut omnis totam.',
                'price' => 47.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 2,
            ),
            83 => 
            array (
                'id' => 85,
                'name' => 'A dolores accusamus facilis.',
                'description' => 'Optio eum itaque delectus sapiente nemo minus quas.',
                'price' => 14.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            84 => 
            array (
                'id' => 86,
                'name' => 'Est dolorem quia at.',
                'description' => 'Dolorum deleniti placeat sapiente maxime et sapiente consequuntur quaerat sint.',
                'price' => 44.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            85 => 
            array (
                'id' => 87,
                'name' => 'Exercitationem repellat nam consectetur voluptates aut et.',
                'description' => 'Illum ipsum vel eos voluptatem at qui nostrum earum enim aut dolores aut recusandae.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 3,
            ),
            86 => 
            array (
                'id' => 88,
                'name' => 'At accusantium nemo ut sit eum quidem.',
                'description' => 'Natus repellendus quos aut aut excepturi id.',
                'price' => 44.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            87 => 
            array (
                'id' => 89,
                'name' => 'Exercitationem ea nostrum vel et.',
                'description' => 'Ullam illum molestiae rerum aut deleniti suscipit.',
                'price' => 23.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 2,
            ),
            88 => 
            array (
                'id' => 90,
                'name' => 'Rerum qui consectetur tempore totam.',
                'description' => 'Aspernatur sapiente ratione earum veniam voluptas quo.',
                'price' => 20.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 3,
            ),
            89 => 
            array (
                'id' => 91,
                'name' => 'Rerum dignissimos voluptates omnis.',
                'description' => 'Suscipit similique eius eveniet eum enim odio.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 3,
            ),
            90 => 
            array (
                'id' => 92,
                'name' => 'Laborum incidunt quod dolor error eius.',
                'description' => 'Dolor voluptatem voluptatem quasi illo sed soluta.',
                'price' => 16.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            91 => 
            array (
                'id' => 93,
                'name' => 'Et est et et sint alias.',
                'description' => 'Nostrum veritatis voluptates cumque assumenda magnam eius qui.',
                'price' => 11.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            92 => 
            array (
                'id' => 94,
                'name' => 'Voluptatem excepturi dignissimos totam molestiae qui possimus.',
                'description' => 'Harum et ut itaque ipsa commodi voluptas occaecati.',
                'price' => 49.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 3,
            ),
            93 => 
            array (
                'id' => 95,
                'name' => 'Unde corporis rerum excepturi omnis sequi et.',
                'description' => 'Rerum in impedit est cupiditate velit ut nostrum accusamus.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            94 => 
            array (
                'id' => 96,
                'name' => 'Illo sint porro omnis incidunt.',
                'description' => 'Placeat sequi corporis sunt aut ullam enim corrupti dolorem tenetur id maxime velit.',
                'price' => 41.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            95 => 
            array (
                'id' => 97,
                'name' => 'Quaerat eveniet beatae similique dolorem sed repellat.',
                'description' => 'Amet temporibus aliquid quam sed quod dignissimos id id sequi deserunt est sed rerum.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 3,
            ),
            96 => 
            array (
                'id' => 98,
                'name' => 'Tempore delectus doloremque suscipit quos voluptas voluptatem vero.',
                'description' => 'Quidem qui omnis vel voluptate id itaque animi natus.',
                'price' => 14.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 3,
            ),
            97 => 
            array (
                'id' => 99,
                'name' => 'Et magni non reiciendis eveniet sit.',
                'description' => 'Officia nihil qui nobis aperiam qui facere eum.',
                'price' => 11.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 1,
            ),
            98 => 
            array (
                'id' => 100,
                'name' => 'Quo beatae ut voluptas.',
                'description' => 'Aperiam vel sint odit repudiandae libero temporibus sed rerum mollitia minus magnam quia.',
                'price' => 47.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:22:57',
                'updated_at' => '2020-07-06 06:22:57',
                'shop_id' => 2,
            ),
            99 => 
            array (
                'id' => 101,
                'name' => 'Provident voluptatibus dolorem soluta porro impedit.',
                'description' => 'Et enim error sit fuga provident nam consequuntur cupiditate fugiat.',
                'price' => 28.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            100 => 
            array (
                'id' => 102,
                'name' => 'Dignissimos fuga ab nihil.',
                'description' => 'Inventore eius voluptates consequuntur aut et nihil omnis sunt.',
                'price' => 44.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            101 => 
            array (
                'id' => 103,
                'name' => 'Ut assumenda qui quam qui mollitia.',
                'description' => 'Magni et voluptate iste qui qui ipsa laudantium corrupti accusantium ut.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            102 => 
            array (
                'id' => 104,
                'name' => 'Id tenetur totam qui.',
                'description' => 'Quia mollitia et molestias assumenda iste voluptas ipsam totam voluptatem saepe veniam est.',
                'price' => 18.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            103 => 
            array (
                'id' => 105,
                'name' => 'Et aut repellat eius beatae.',
                'description' => 'Modi optio non blanditiis quisquam consequatur non.',
                'price' => 19.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            104 => 
            array (
                'id' => 106,
                'name' => 'Molestiae nam consectetur laborum animi tempore.',
                'description' => 'Ipsa modi sunt maiores veritatis voluptatibus est recusandae.',
                'price' => 31.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            105 => 
            array (
                'id' => 107,
                'name' => 'Pariatur sequi et temporibus non eius.',
                'description' => 'Non ipsa optio ab optio aut dolore cupiditate ab voluptate id perspiciatis doloremque.',
                'price' => 17.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            106 => 
            array (
                'id' => 108,
                'name' => 'Nihil qui accusamus ad harum ab aperiam.',
                'description' => 'Reiciendis aut et accusantium doloribus aut ut.',
                'price' => 20.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            107 => 
            array (
                'id' => 109,
                'name' => 'Omnis quaerat non soluta sit ex autem.',
                'description' => 'Cupiditate qui qui recusandae fugit quas perferendis consequatur natus tempora autem exercitationem.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            108 => 
            array (
                'id' => 110,
                'name' => 'Voluptatem sequi neque veniam officia repudiandae.',
                'description' => 'Corrupti reprehenderit quia laudantium tempore labore maxime.',
                'price' => 50.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            109 => 
            array (
                'id' => 111,
                'name' => 'Molestiae maiores sunt quos quibusdam molestiae placeat.',
                'description' => 'Eligendi illum consequatur quis nihil ad sint beatae labore.',
                'price' => 10.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            110 => 
            array (
                'id' => 112,
                'name' => 'Et illo velit repudiandae ea.',
                'description' => 'Nobis aliquid alias aut nisi minima pariatur.',
                'price' => 13.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            111 => 
            array (
                'id' => 113,
                'name' => 'Sit omnis ad ducimus eos molestiae.',
                'description' => 'Nostrum sed nesciunt vero veniam sed harum amet dolor dolorum magni voluptatum ab dignissimos.',
                'price' => 17.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            112 => 
            array (
                'id' => 114,
                'name' => 'Velit omnis aliquam quis inventore.',
                'description' => 'Omnis tenetur et consequatur voluptatibus animi aut ut consequatur eaque veritatis suscipit.',
                'price' => 31.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            113 => 
            array (
                'id' => 115,
                'name' => 'Consequatur perferendis qui itaque blanditiis.',
                'description' => 'Rerum corporis maxime officiis enim sequi beatae dolor ipsum exercitationem non hic voluptatem suscipit.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            114 => 
            array (
                'id' => 116,
                'name' => 'Possimus accusantium aspernatur unde assumenda nemo ipsa.',
                'description' => 'Explicabo fugiat sed aliquam labore tempora repellendus.',
                'price' => 12.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            115 => 
            array (
                'id' => 117,
                'name' => 'Aut delectus maxime est quisquam.',
                'description' => 'Rerum iusto aut vero perferendis sequi sapiente accusantium earum cumque iure.',
                'price' => 30.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            116 => 
            array (
                'id' => 118,
                'name' => 'Nulla dicta sit illum voluptatibus.',
                'description' => 'Sunt optio quo nostrum est quidem voluptates suscipit dicta consequuntur.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            117 => 
            array (
                'id' => 119,
                'name' => 'Unde officiis provident libero quod.',
                'description' => 'Pariatur vitae facere non velit sit cum aut aliquid tempore eos corporis quia.',
                'price' => 43.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            118 => 
            array (
                'id' => 120,
                'name' => 'Ipsam fugiat voluptas voluptas.',
                'description' => 'Id error aut voluptatibus eum ullam qui velit id eum quos sunt.',
                'price' => 30.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            119 => 
            array (
                'id' => 121,
                'name' => 'Iure eius sequi quas laborum totam.',
                'description' => 'Autem soluta consequuntur vel labore molestiae vel totam dignissimos repudiandae esse ab asperiores.',
                'price' => 43.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            120 => 
            array (
                'id' => 122,
                'name' => 'Voluptatem totam aspernatur et deleniti.',
                'description' => 'Et amet consectetur sit rem optio nobis.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            121 => 
            array (
                'id' => 123,
                'name' => 'Dolores itaque quis quam dicta molestiae.',
                'description' => 'Non nisi libero at non saepe est est eaque reprehenderit non.',
                'price' => 19.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            122 => 
            array (
                'id' => 124,
                'name' => 'Et maiores voluptates quia laudantium.',
                'description' => 'Ipsam cum quam commodi facilis voluptas inventore impedit consequuntur voluptates vel.',
                'price' => 23.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            123 => 
            array (
                'id' => 125,
                'name' => 'Quas ut blanditiis non explicabo quo praesentium.',
                'description' => 'Enim esse nemo aut quo minima deleniti.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            124 => 
            array (
                'id' => 126,
                'name' => 'Temporibus quam doloribus totam aut.',
                'description' => 'Voluptate perspiciatis ratione natus quas dolor voluptas repellat ex rerum perferendis sapiente.',
                'price' => 20.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            125 => 
            array (
                'id' => 127,
                'name' => 'Iure recusandae quas aliquid fugit.',
                'description' => 'Nam incidunt voluptates dolores sint non error neque fugit rerum quidem illo est omnis.',
                'price' => 28.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            126 => 
            array (
                'id' => 128,
                'name' => 'Impedit ducimus et officia consequatur.',
                'description' => 'Et ut recusandae modi accusamus aut et est dolor commodi est iusto.',
                'price' => 43.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            127 => 
            array (
                'id' => 129,
                'name' => 'Porro et consequatur consequatur dignissimos rerum dolore.',
                'description' => 'Culpa ut dolores dolore culpa omnis laborum ut facere ut.',
                'price' => 41.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            128 => 
            array (
                'id' => 130,
                'name' => 'Deleniti dolores reiciendis nihil ut.',
                'description' => 'Doloremque qui molestiae excepturi dolorum omnis aliquid magni cupiditate repellat quaerat accusamus laudantium.',
                'price' => 36.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            129 => 
            array (
                'id' => 131,
                'name' => 'Maiores quibusdam qui numquam eum quia.',
                'description' => 'Et veritatis quo eos ut animi magni.',
                'price' => 15.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            130 => 
            array (
                'id' => 132,
                'name' => 'Numquam eum ab perspiciatis.',
                'description' => 'Laborum illum est vitae ut officiis sit.',
                'price' => 14.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            131 => 
            array (
                'id' => 133,
                'name' => 'Autem ducimus sunt et rerum velit et.',
                'description' => 'Est consequatur eos et aperiam quod ut rerum iusto nihil.',
                'price' => 28.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            132 => 
            array (
                'id' => 134,
                'name' => 'Dolores quae sequi et.',
                'description' => 'Est at id corrupti sed laboriosam ut optio non.',
                'price' => 49.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            133 => 
            array (
                'id' => 135,
                'name' => 'Est dignissimos temporibus voluptate aliquid.',
                'description' => 'Ipsum quidem enim hic tempore et distinctio dolores voluptas.',
                'price' => 11.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            134 => 
            array (
                'id' => 136,
                'name' => 'Eos fuga voluptate quia cum corporis.',
                'description' => 'Sed eveniet praesentium commodi iure voluptatem aut deserunt animi earum itaque et qui.',
                'price' => 15.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            135 => 
            array (
                'id' => 137,
                'name' => 'Natus voluptas eius aperiam.',
                'description' => 'Adipisci sunt omnis voluptatem qui excepturi dolorum ut nostrum amet eos repellendus qui fugiat.',
                'price' => 10.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            136 => 
            array (
                'id' => 138,
                'name' => 'Quos illum libero consequatur.',
                'description' => 'Nam aut amet ipsam quis animi et.',
                'price' => 16.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            137 => 
            array (
                'id' => 139,
                'name' => 'Deleniti laboriosam laudantium numquam tenetur culpa totam.',
                'description' => 'Non maiores et voluptatibus ut reiciendis quod fugit in quas quam error earum exercitationem.',
                'price' => 25.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            138 => 
            array (
                'id' => 140,
                'name' => 'Id et vel sunt reprehenderit alias.',
                'description' => 'Quidem veritatis ipsam ut deleniti est voluptates sapiente rerum consequatur saepe voluptate enim.',
                'price' => 41.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            139 => 
            array (
                'id' => 141,
                'name' => 'Ducimus est labore et.',
                'description' => 'Quaerat molestias delectus dolor et et autem.',
                'price' => 22.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            140 => 
            array (
                'id' => 142,
                'name' => 'Occaecati rem et eius.',
                'description' => 'Labore eos exercitationem porro occaecati repudiandae blanditiis iure omnis accusamus autem porro animi blanditiis.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            141 => 
            array (
                'id' => 143,
                'name' => 'Id voluptas est sed facilis consequatur.',
                'description' => 'Voluptatem minima explicabo voluptas ipsam suscipit excepturi in minus dolorem aut delectus ipsa qui.',
                'price' => 20.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            142 => 
            array (
                'id' => 144,
                'name' => 'Quasi et atque eos et.',
                'description' => 'Cum temporibus repellendus et dolorum natus ad aut cumque doloremque est aliquam.',
                'price' => 12.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            143 => 
            array (
                'id' => 145,
                'name' => 'Necessitatibus vel illum sit consectetur vitae veniam.',
                'description' => 'Non dolor dolores voluptatum quis assumenda corporis mollitia consequuntur neque.',
                'price' => 40.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            144 => 
            array (
                'id' => 146,
                'name' => 'Id et molestiae laudantium ut corrupti at.',
                'description' => 'Veritatis ratione corrupti assumenda deleniti corporis unde voluptatem.',
                'price' => 12.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 1,
            ),
            145 => 
            array (
                'id' => 147,
                'name' => 'Mollitia quo ab asperiores praesentium est.',
                'description' => 'Reiciendis similique amet non excepturi natus sit.',
                'price' => 33.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            146 => 
            array (
                'id' => 148,
                'name' => 'Deleniti voluptate voluptatem enim accusamus.',
                'description' => 'Voluptates nisi et placeat qui doloremque qui dicta optio repellendus quo voluptas tenetur.',
                'price' => 23.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            147 => 
            array (
                'id' => 149,
                'name' => 'Impedit recusandae tempora qui qui.',
                'description' => 'Vel autem est magnam molestias dolorum nam nostrum vel quo nobis.',
                'price' => 45.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 2,
            ),
            148 => 
            array (
                'id' => 150,
                'name' => 'Tempora nihil vel voluptatem laboriosam error voluptas.',
                'description' => 'In eligendi libero quam aut nesciunt vero maxime fugit rerum quas.',
                'price' => 42.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:23:20',
                'updated_at' => '2020-07-06 06:23:20',
                'shop_id' => 3,
            ),
            149 => 
            array (
                'id' => 151,
                'name' => 'Ratione commodi quisquam necessitatibus velit quis necessitatibus.',
                'description' => 'Perferendis reiciendis praesentium cum dolores sed aut ipsa commodi fugit.',
                'price' => 11.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            150 => 
            array (
                'id' => 152,
                'name' => 'Sequi similique ab recusandae et et molestias.',
                'description' => 'Est voluptatum eius et quae et et et doloribus.',
                'price' => 21.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            151 => 
            array (
                'id' => 153,
                'name' => 'Rerum quia recusandae iste.',
                'description' => 'Molestias nulla ullam dolores ducimus ut doloribus autem.',
                'price' => 49.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            152 => 
            array (
                'id' => 154,
                'name' => 'Id est repellendus et ullam maxime nihil.',
                'description' => 'Dolores sed ex et omnis quaerat non asperiores consequatur alias sint quisquam cumque.',
                'price' => 12.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            153 => 
            array (
                'id' => 155,
                'name' => 'Esse quia eum a aspernatur odit veniam.',
                'description' => 'Maiores quaerat dignissimos beatae nisi provident eos et rerum unde laboriosam.',
                'price' => 41.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            154 => 
            array (
                'id' => 156,
                'name' => 'Eos ad et ea rerum ut modi.',
                'description' => 'Sed voluptas tempore dolorem omnis cumque quod voluptatibus et qui qui molestiae.',
                'price' => 39.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            155 => 
            array (
                'id' => 157,
                'name' => 'Ut facere voluptatem nihil commodi quas.',
                'description' => 'Itaque aspernatur ex animi officia est nobis laboriosam ea magni magni reiciendis a.',
                'price' => 14.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            156 => 
            array (
                'id' => 158,
                'name' => 'Ex debitis beatae quae eum est.',
                'description' => 'Quos eum consectetur dolor sapiente nulla modi similique ex laborum dolor iusto delectus velit.',
                'price' => 37.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            157 => 
            array (
                'id' => 159,
                'name' => 'Ut quam est dolorem quidem eius.',
                'description' => 'Mollitia asperiores eos ducimus perspiciatis ut nihil et veritatis laborum quia veritatis distinctio sit omnis.',
                'price' => 36.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            158 => 
            array (
                'id' => 160,
                'name' => 'Enim excepturi ut voluptate.',
                'description' => 'Id voluptatem veniam nemo laudantium occaecati vitae molestias non omnis veniam veritatis.',
                'price' => 31.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            159 => 
            array (
                'id' => 161,
                'name' => 'Accusamus nisi suscipit unde.',
                'description' => 'Accusantium maiores recusandae autem corrupti laborum recusandae voluptas occaecati ut velit.',
                'price' => 23.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            160 => 
            array (
                'id' => 162,
                'name' => 'Ipsa necessitatibus blanditiis sit recusandae dolorum.',
                'description' => 'Nesciunt est repudiandae earum tenetur aut vitae numquam voluptatibus natus dolores minus qui.',
                'price' => 37.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            161 => 
            array (
                'id' => 163,
                'name' => 'Cum alias placeat nobis dolorum.',
                'description' => 'Quo eos est perspiciatis amet aut laborum suscipit quidem.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            162 => 
            array (
                'id' => 164,
                'name' => 'Veritatis similique libero rerum debitis doloribus provident.',
                'description' => 'Maiores sunt laudantium est corporis reiciendis consequuntur blanditiis quasi eveniet alias sed.',
                'price' => 21.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            163 => 
            array (
                'id' => 165,
                'name' => 'Nihil voluptate beatae illum.',
                'description' => 'Sit eum nemo quia voluptatibus fugit nobis porro earum maiores.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            164 => 
            array (
                'id' => 166,
                'name' => 'Ad odio et cumque officiis sint.',
                'description' => 'Quae incidunt necessitatibus qui nam sit aliquam fugit placeat sapiente perferendis dolor non.',
                'price' => 20.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            165 => 
            array (
                'id' => 167,
                'name' => 'Accusamus nobis quis soluta ut quia.',
                'description' => 'Veniam ipsam deserunt quo perspiciatis consectetur consequatur quas vel omnis aliquam aperiam molestiae optio.',
                'price' => 41.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            166 => 
            array (
                'id' => 168,
                'name' => 'Adipisci quasi et non.',
                'description' => 'Fuga nam sunt amet quibusdam rerum nam.',
                'price' => 11.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            167 => 
            array (
                'id' => 169,
                'name' => 'Qui cumque optio cupiditate.',
                'description' => 'Quia eaque modi nostrum iste quod dolor ad.',
                'price' => 21.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            168 => 
            array (
                'id' => 170,
                'name' => 'Perferendis quis est quidem.',
                'description' => 'Autem et nihil deserunt sint sequi ad voluptate facere nesciunt et accusantium provident.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            169 => 
            array (
                'id' => 171,
                'name' => 'Accusantium deserunt illum pariatur ab voluptatem ea.',
                'description' => 'Modi fugit quia et placeat illo corporis quos dolore.',
                'price' => 42.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            170 => 
            array (
                'id' => 172,
                'name' => 'Facere aliquid voluptas aperiam optio et.',
                'description' => 'Est sed eligendi aperiam earum qui voluptatem fuga in inventore dignissimos architecto.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            171 => 
            array (
                'id' => 173,
                'name' => 'Eos sunt eius a perferendis cumque repellendus.',
                'description' => 'Harum accusamus dicta est repellendus nobis iusto exercitationem est.',
                'price' => 12.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            172 => 
            array (
                'id' => 174,
                'name' => 'Dolore dolores corrupti dignissimos.',
                'description' => 'Soluta asperiores consequatur vitae est ea quisquam voluptatem velit.',
                'price' => 11.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            173 => 
            array (
                'id' => 175,
                'name' => 'Voluptate voluptate quo beatae qui tenetur debitis.',
                'description' => 'Enim pariatur quia eum magnam aperiam qui quibusdam laboriosam aut.',
                'price' => 12.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            174 => 
            array (
                'id' => 176,
                'name' => 'Voluptate magni repudiandae sed rerum repudiandae.',
                'description' => 'Quo repudiandae in beatae molestias quod laudantium facere quia consectetur cum facilis.',
                'price' => 27.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            175 => 
            array (
                'id' => 177,
                'name' => 'Voluptates voluptatibus vel aliquid iusto.',
                'description' => 'Saepe molestiae deserunt voluptatibus soluta consequatur tempora reiciendis et maxime corporis.',
                'price' => 42.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            176 => 
            array (
                'id' => 178,
                'name' => 'Aspernatur alias voluptates neque.',
                'description' => 'Unde facilis eos cumque non qui dolorem.',
                'price' => 10.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            177 => 
            array (
                'id' => 179,
                'name' => 'Ab officiis sed qui autem qui.',
                'description' => 'Consectetur fugit minus dolorum possimus facere sed veniam natus aut omnis.',
                'price' => 43.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            178 => 
            array (
                'id' => 180,
                'name' => 'Esse cum odit maxime.',
                'description' => 'Quo libero eius deserunt debitis a quod rerum voluptatibus soluta officia.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            179 => 
            array (
                'id' => 181,
                'name' => 'Ut libero itaque sit.',
                'description' => 'Omnis labore enim similique ut quibusdam nobis maxime sunt.',
                'price' => 11.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            180 => 
            array (
                'id' => 182,
                'name' => 'Veniam aliquid iusto dicta aut.',
                'description' => 'Eveniet deserunt at rerum ipsam nostrum saepe fugiat voluptates eveniet est natus ipsum ea.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            181 => 
            array (
                'id' => 183,
                'name' => 'Blanditiis omnis ducimus et modi maiores necessitatibus.',
                'description' => 'Corporis voluptatem quis in suscipit nihil nisi expedita corrupti.',
                'price' => 24.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            182 => 
            array (
                'id' => 184,
                'name' => 'Aperiam soluta molestiae excepturi a nostrum ipsa.',
                'description' => 'Aliquam alias beatae ut voluptas quisquam sequi est iusto.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            183 => 
            array (
                'id' => 185,
                'name' => 'Dolores recusandae dolorem reiciendis saepe minus est.',
                'description' => 'Reiciendis illum est labore et vero veritatis.',
                'price' => 28.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            184 => 
            array (
                'id' => 186,
                'name' => 'Culpa fugiat et soluta.',
                'description' => 'Eligendi sit aspernatur dolores delectus magni eos vitae autem ut earum sed dolore similique.',
                'price' => 40.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            185 => 
            array (
                'id' => 187,
                'name' => 'Quod laborum beatae ab.',
                'description' => 'Alias animi ea eos tempora quia numquam laudantium aspernatur possimus similique fugiat in quia.',
                'price' => 35.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            186 => 
            array (
                'id' => 188,
                'name' => 'Quia cumque corporis maiores incidunt hic.',
                'description' => 'Atque vero voluptatibus aut autem quia et consequatur deserunt fuga voluptatem iure.',
                'price' => 32.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            187 => 
            array (
                'id' => 189,
                'name' => 'Alias consequuntur aut placeat omnis id.',
                'description' => 'Sint sunt et et velit commodi quis provident est nesciunt molestiae corrupti nostrum.',
                'price' => 47.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            188 => 
            array (
                'id' => 190,
                'name' => 'Voluptatem omnis dicta dolore voluptatem est facilis.',
                'description' => 'Provident magni eligendi voluptatem consequuntur eaque laboriosam.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            189 => 
            array (
                'id' => 191,
                'name' => 'Rerum dicta est et quia.',
                'description' => 'Vel corrupti molestiae culpa pariatur hic cupiditate ullam natus voluptatem quos vero sit.',
                'price' => 27.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            190 => 
            array (
                'id' => 192,
                'name' => 'Esse nam consectetur aut doloribus quam.',
                'description' => 'Ut doloremque quisquam occaecati vitae accusamus voluptatem.',
                'price' => 49.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 1,
            ),
            191 => 
            array (
                'id' => 193,
                'name' => 'Quisquam qui sint a deleniti quia.',
                'description' => 'Repellat et facilis ab magnam cumque recusandae autem sunt ut sed iure nulla.',
                'price' => 26.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            192 => 
            array (
                'id' => 194,
                'name' => 'Ut veritatis dignissimos neque quod nobis necessitatibus.',
                'description' => 'Voluptates deleniti quo deleniti est dolorum provident veritatis omnis.',
                'price' => 38.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            193 => 
            array (
                'id' => 195,
                'name' => 'Cum dignissimos accusamus debitis placeat minima.',
                'description' => 'Cupiditate optio sed impedit sunt adipisci et doloremque.',
                'price' => 49.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            194 => 
            array (
                'id' => 196,
                'name' => 'Consequatur hic aperiam qui corrupti placeat nobis.',
                'description' => 'Sed quo temporibus eveniet impedit debitis dolorum.',
                'price' => 34.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            195 => 
            array (
                'id' => 197,
                'name' => 'Facere velit earum officiis ut voluptatibus.',
                'description' => 'Vitae et saepe et voluptates vel itaque nulla nihil est modi.',
                'price' => 26.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            196 => 
            array (
                'id' => 198,
                'name' => 'Dolorem et molestias eum officia architecto.',
                'description' => 'Quis vitae porro veniam esse dolor perferendis maxime.',
                'price' => 46.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 3,
            ),
            197 => 
            array (
                'id' => 199,
                'name' => 'Dolores voluptatem quo laboriosam et ea necessitatibus et.',
                'description' => 'Veniam voluptates voluptatem quos consequatur et et nostrum et aliquam nihil.',
                'price' => 34.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
            198 => 
            array (
                'id' => 200,
                'name' => 'Laboriosam et expedita voluptas ratione dignissimos est.',
                'description' => 'Sit dolor aut dolor fugiat qui non omnis tenetur sint quia magnam veritatis ducimus.',
                'price' => 12.0,
                'cover_img' => NULL,
                'created_at' => '2020-07-06 06:24:36',
                'updated_at' => '2020-07-06 06:24:36',
                'shop_id' => 2,
            ),
        ));
        
        
    }
}